### ISSUE TITLE
Grunt-jade, express.js and i18n

### ISSUE THREAD

**Issue by pagoad** [AdesisNetlife/grunt-jade-i18n#21]
I use Grunt, Jade and express.js.
In my jade template i Use i18n - https://github.com/mashpie/i18n-node/
like this:

    span #{__('agency')}

When i start grunt serve it is ok, it works excellent. But if i want to compile it grunt-jade tell me that

    span #{__('agency')}
    undefined is not a function

Could you tell me how in grunt-jade i could define internationalization like this:

    #{__('agency')}

not like:

    #{$i18n.agency}

Because i18n in express js define it in different way.

**Comment by h2non** [comment]
Have you tried binding the i18n-node helper function to the Jade compiler?:

```js
var i18n = require('i18n-node') // load
```

```js
jade: {
  options: {
    data: function() {
      return {
         __: i18n.__
      }
    }
  }
}
```

Remember that `grunt-jade-i18n` uses internally [grunt-contrib-jade](https://github.com/gruntjs/grunt-contrib-jade), so you can pass any option value that's supported by the original task

**Comment by pagoad** [comment]
Hi.
Thx for help.
I use it and we are step closer now :)

    i18n: {
          locales: '<%= yeogurt.server %>/config/locales/en.json'
        },
        data:function() {
                    return {
                  __: i18n.__
         }

Now i have: 
    >Cannot read property 'agency' of undefined

**Comment by pagoad** [comment]
All right :)
I add i18n configure:

      var i18n = require('i18n');
      i18n.configure({
             locales: ['en', 'pl'],
             cookie: 'yourcookiename',
             defaultLocale: 'pl',
             directory: 'server/config/locales/'
       });

And it's work. Thx for help again! :)
