### ISSUE TITLE
Customized file name with lang when distributing 

### ISSUE THREAD

**Issue by wxqee** [AdesisNetlife/grunt-jade-i18n#25]
Is there a way to customize a file name with specified language when distributing?

For example,
```javascript
/* now */
files: {
  "dist/subfolder/index.html": "www/subfolder/index.jade"
}
```
then files generated are "dist/subfolder/zh_CN/index.html" and "dist/subfolder/en_US/index.html", **but I want it to be "dist/zh_CN/subfolder/index.html"**.  So I need something like this:
```javascript
/* wanted */
files: {
  "dist/{{language}}/subfolder/index.html": "www/subfolder/index.jade"
}
```
So `{{language}}` will be filled with "zh_CN" and "en_US" during different distributes.

**Comment by h2non** [comment]
You cannot do that at Grunt runtime level. 
You should use another task to copy files to the desired folder structure
